import json
import os
import psycopg2.extras
from src.store.postgres_database import PostgresDatabase

# When enabled, agents get access to the real-AWS observability + data
# integrity tools (query_cloudwatch_logs, list_s3_objects, read_s3_object,
# describe_lambda_invocation, check_table_staleness, cleanup_partial_write,
# verify_row_count_matches_expected) defined in
# src/domain/tools/aws_observability_tools.py, backed by the LocalStack lab.
# Off by default so normal NemoGuard operation (no lab running, no boto3
# needed) is completely unaffected.
LOCALSTACK_LAB_ENABLED = os.environ.get("NEMOGUARD_LOCALSTACK_LAB", "0") == "1"

def query_logs(incident_id: str, keyword: str = "") -> str:
    """Queries the log_event table for the primary_run_id associated with an incident."""
    db = PostgresDatabase(os.environ.get("POSTGRES_URL", "postgresql://nemoguard:nemoguard_password@postgres:5432/nemoguard_db"))
    with db.get_connection() as conn:
        cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
        
        # Get primary run ID
        cursor.execute("SELECT primary_run_id FROM incident WHERE incident_id = %s", (incident_id,))
        row = cursor.fetchone()
        if not row:
            return f"Incident {incident_id} not found."
        
        run_id = row['primary_run_id']
        if not run_id:
            return f"No primary_run_id associated with incident {incident_id}."
            
        # Get logs
        # NOTE: log_event's actual column is `component`, not `source` (see migrations/002_domain_model.sql
        # and src/store/schema.sql). Using `source` here previously caused a hard Postgres error
        # ('column "source" does not exist'), which silently broke RCA investigation for every incident
        # and caused the Grounding Critic to correctly (but unhelpfully) flag every plan as NEEDS_REVIEW.
        if keyword:
            cursor.execute(
                "SELECT timestamp, level, component, message FROM log_event WHERE run_id = %s AND (message LIKE %s OR component LIKE %s) ORDER BY timestamp ASC LIMIT 50",
                (run_id, f"%{keyword}%", f"%{keyword}%")
            )
        else:
            cursor.execute(
                "SELECT timestamp, level, component, message FROM log_event WHERE run_id = %s AND level IN ('ERROR', 'WARN') ORDER BY timestamp ASC LIMIT 50",
                (run_id,)
            )
            
        logs = [dict(r) for r in cursor.fetchall()]
        if not logs:
            return f"No logs found matching criteria for run {run_id}."
            
        return json.dumps(logs, indent=2)


def get_cmdb_context(service_name: str) -> str:
    """Fetches downstream/upstream dependencies from the CMDB database."""
    db = PostgresDatabase(os.environ.get("POSTGRES_URL", "postgresql://nemoguard:nemoguard_password@postgres:5432/nemoguard_db"))
    with db.get_connection() as conn:
        cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
        
        # We find jobs that match the service_name, then get their asset_dependencies
        cursor.execute("SELECT job_id, job_name FROM job WHERE job_id ILIKE %s OR job_name ILIKE %s", (f"%{service_name}%", f"%{service_name}%"))
        jobs = cursor.fetchall()
        
        if not jobs:
            # Fallback: if no exact match, return recent assets to ensure LLM has context
            cursor.execute("SELECT asset_name, owner, sla_minutes FROM business_asset LIMIT 5")
            assets = cursor.fetchall()
            if not assets:
                return f"Service {service_name} not found in CMDB, and CMDB is empty."
            return json.dumps({"query": service_name, "note": "Exact match not found, showing available downstream assets in CMDB", "downstream_assets": [dict(a) for a in assets]}, indent=2)
            
        job_id = jobs[0]['job_id']
        cursor.execute('''
            SELECT b.asset_name, b.asset_type, b.owner, b.sla_minutes, b.criticality 
            FROM asset_dependency a
            JOIN business_asset b ON a.asset_id = b.asset_id
            WHERE a.job_id = %s
        ''', (job_id,))
        assets = cursor.fetchall()
        
        results = {
            jobs[0]['job_name']: {
                "downstream": [dict(a) for a in assets]
            }
        }
        
        return json.dumps({"query": service_name, "matches": results}, indent=2)

# Real runbook DOCUMENTS (not just DB rows): Word/PDF files an agent can
# actually read to get the full diagnostic/remediation/verification
# procedure for a given failure mode. Maps a service/failure-type keyword
# to the doc's filename in data/runbook_docs/ (generated by
# data/runbook_docs/generate_docs.py -- real .docx/.pdf files on disk, not
# strings embedded in Python).
RUNBOOK_DOCUMENT_INDEX = {
    "schema_drift": "RB_SCHEMA_DRIFT_DOC.docx",
    "customer_profile": "RB_SCHEMA_DRIFT_DOC.docx",
    "ingest": "RB_SCHEMA_DRIFT_DOC.docx",
    "partial_write": "RB_PARTIAL_WRITE_DOC.docx",
    "order_events": "RB_PARTIAL_WRITE_DOC.docx",
    "poison_pill": "RB_POISON_PILL_DOC.docx",
    "notification": "RB_POISON_PILL_DOC.docx",
    "sqs": "RB_POISON_PILL_DOC.docx",
    "pipeline": "RB_PIPELINE_STEP_FAILURE_DOC.pdf",
    "step_function": "RB_PIPELINE_STEP_FAILURE_DOC.pdf",
    "state_machine": "RB_PIPELINE_STEP_FAILURE_DOC.pdf",
}

_RUNBOOK_DOCS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))), "data", "runbook_docs")


def _extract_docx_text(path: str) -> str:
    from docx import Document
    doc = Document(path)
    parts = []
    for para in doc.paragraphs:
        if para.text.strip():
            parts.append(para.text)
    return "\n".join(parts)


def _extract_pdf_text(path: str) -> str:
    from pypdf import PdfReader
    reader = PdfReader(path)
    parts = [page.extract_text() or "" for page in reader.pages]
    return "\n".join(parts)


def read_runbook_document(query: str) -> str:
    """Reads the ACTUAL text content of a real runbook Word/PDF document
    matching the query keyword (e.g. 'schema_drift', 'partial_write',
    'poison_pill', 'pipeline'), extracted live from the file on disk --
    not a hardcoded string. Use this to get the full diagnostic,
    remediation, and verification procedure for a failure type, beyond
    what get_runbook's database-row summary provides."""
    key = query.strip().lower()
    filename = None
    for keyword, fname in RUNBOOK_DOCUMENT_INDEX.items():
        if keyword in key:
            filename = fname
            break
    if not filename:
        available = ", ".join(sorted(set(RUNBOOK_DOCUMENT_INDEX.keys())))
        return f"No runbook document found matching '{query}'. Available keywords: {available}"

    path = os.path.join(_RUNBOOK_DOCS_DIR, filename)
    if not os.path.exists(path):
        return f"Runbook document {filename} not found on disk at {path}. Run data/runbook_docs/generate_docs.py to generate it."

    try:
        if filename.endswith(".docx"):
            text = _extract_docx_text(path)
        elif filename.endswith(".pdf"):
            text = _extract_pdf_text(path)
        else:
            return f"Unsupported runbook document format: {filename}"
        return f"[Extracted from {filename}]\n\n{text}"
    except Exception as e:
        return f"Error reading runbook document {filename}: {e}"


def get_runbook(service_name: str) -> str:
    """Fetches Runbook based on service name from the database."""
    db = PostgresDatabase(os.environ.get("POSTGRES_URL", "postgresql://nemoguard:nemoguard_password@postgres:5432/nemoguard_db"))
    with db.get_connection() as conn:
        cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
        cursor.execute("SELECT title, incident_type, prerequisites_json, verification_json, rollback_json FROM runbook WHERE title ILIKE %s OR runbook_id ILIKE %s", (f"%{service_name}%", f"%{service_name}%"))
        rbs = cursor.fetchall()
        if rbs:
            return json.dumps([dict(r) for r in rbs], indent=2)
            
        # Fallback: return any available runbook in the demo environment
        cursor.execute("SELECT title, incident_type, prerequisites_json, verification_json, rollback_json FROM runbook LIMIT 3")
        rbs = cursor.fetchall()
        if rbs:
            return json.dumps([dict(r) for r in rbs], indent=2)
            
    return f"No runbook found for service {service_name}. Default recommendation: Escalate to L3."

# The OpenAI JSON schema definitions for the tools
AGENT_TOOLS_SCHEMA = [
    {
        "type": "function",
        "function": {
            "name": "query_logs",
            "description": "Queries logs for a given incident_id. Use this to find errors or trace the failure.",
            "parameters": {
                "type": "object",
                "properties": {
                    "incident_id": {
                        "type": "string",
                        "description": "The ID of the incident (e.g. INC-12345)"
                    },
                    "keyword": {
                        "type": "string",
                        "description": "Optional keyword to filter logs (e.g. 'schema' or 'timeout')"
                    }
                },
                "required": ["incident_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_cmdb_context",
            "description": "Fetches upstream and downstream dependencies for a given service or job name from the CMDB.",
            "parameters": {
                "type": "object",
                "properties": {
                    "service_name": {
                        "type": "string",
                        "description": "The name of the service, job, or table (e.g. 'customer_profile')"
                    }
                },
                "required": ["service_name"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_runbook",
            "description": "Fetches recovery runbooks and standard operating procedures for a given service or job.",
            "parameters": {
                "type": "object",
                "properties": {
                    "service_name": {
                        "type": "string",
                        "description": "The name of the service or job to get a runbook for."
                    }
                },
                "required": ["service_name"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "read_runbook_document",
            "description": "Reads the FULL text of a real runbook Word/PDF document for a failure type (e.g. 'schema_drift', 'partial_write', 'poison_pill', 'pipeline'/'step_function'), extracted live from the actual .docx/.pdf file. Use this when get_runbook's short database summary isn't detailed enough and you need the complete diagnostic/remediation/verification procedure.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Keyword identifying which runbook document to read, e.g. 'schema_drift', 'partial_write', 'poison_pill', 'pipeline'."
                    }
                },
                "required": ["query"]
            }
        }
    }
]

# Real-AWS observability + data-integrity tools, only advertised to the LLM
# when the LocalStack lab is enabled (see LOCALSTACK_LAB_ENABLED above).
# These let agents look at the ACTUAL failure evidence (real CloudWatch
# Logs, real S3 objects, real Lambda metrics) and actually check/repair
# real database state (partial-write staleness + cleanup + verification)
# instead of being limited to NemoGuard's own synthetic metadata tables.
LOCALSTACK_LAB_TOOLS_SCHEMA = [
    {
        "type": "function",
        "function": {
            "name": "query_cloudwatch_logs",
            "description": "Queries REAL CloudWatch Logs for a given log group (e.g. '/aws/lambda/nemoguard-ingest-job'), optionally filtered by a keyword. Use this for the full, raw application log output of a job -- more complete than query_logs, which only sees what the job wrote back into NemoGuard's own metadata table.",
            "parameters": {
                "type": "object",
                "properties": {
                    "log_group_name": {"type": "string", "description": "CloudWatch log group name, e.g. '/aws/lambda/nemoguard-ingest-job' or '/aws/lambda/nemoguard-order-events-job'."},
                    "filter_pattern": {"type": "string", "description": "Optional substring to filter log messages by."},
                    "limit": {"type": "integer", "description": "Max number of log events to return (default 50)."}
                },
                "required": ["log_group_name"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "list_s3_objects",
            "description": "Lists real objects in a real S3 bucket under a prefix. Use to check what input files exist/existed for a run, or to find related batches.",
            "parameters": {
                "type": "object",
                "properties": {
                    "bucket": {"type": "string", "description": "S3 bucket name, e.g. 'nemoguard-lab-data'."},
                    "prefix": {"type": "string", "description": "Key prefix to filter by, e.g. 'customer_profile/' or 'order_events/'."},
                    "max_keys": {"type": "integer", "description": "Max objects to list (default 20)."}
                },
                "required": ["bucket"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "read_s3_object",
            "description": "Reads the actual content of a real S3 object -- use to inspect the exact input data that caused a job to fail (confirm a schema mismatch, malformed record, etc. directly).",
            "parameters": {
                "type": "object",
                "properties": {
                    "bucket": {"type": "string", "description": "S3 bucket name."},
                    "key": {"type": "string", "description": "Full S3 object key to read."}
                },
                "required": ["bucket", "key"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "describe_lambda_invocation",
            "description": "Fetches real recent CloudWatch metrics (Invocations, Errors, Duration) for a Lambda function over the last 30 minutes -- use to determine if this is a one-off failure or a sustained error spike.",
            "parameters": {
                "type": "object",
                "properties": {
                    "function_name": {"type": "string", "description": "Lambda function name, e.g. 'nemoguard-ingest-job'."}
                },
                "required": ["function_name"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "check_table_staleness",
            "description": "REQUIRED before recommending a rerun of any job that writes to a database table: checks whether a previous run left partial/stale data (actual row count for this run_id vs. expected). If is_stale_or_partial is true, cleanup_partial_write MUST be called before a rerun step is proposed, otherwise the rerun would double-write already-committed rows.",
            "parameters": {
                "type": "object",
                "properties": {
                    "table_name": {"type": "string", "description": "Table to check, e.g. 'order_events'."},
                    "run_id": {"type": "string", "description": "The run_id whose data to check."},
                    "expected_row_count": {"type": "integer", "description": "Optional explicit expected row count; if omitted, looked up from the run manifest when available."}
                },
                "required": ["table_name", "run_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "cleanup_partial_write",
            "description": "Deletes rows for a specific run_id from a table to clean up a genuine partial write before a rerun. ALWAYS call with dry_run=true first to see the impact; only call with dry_run=false (which actually deletes data) after that has been reviewed/approved.",
            "parameters": {
                "type": "object",
                "properties": {
                    "table_name": {"type": "string", "description": "Table to clean up, e.g. 'order_events'."},
                    "run_id": {"type": "string", "description": "The run_id whose partial rows to delete."},
                    "dry_run": {"type": "boolean", "description": "If true (default), only reports what would be deleted without deleting anything."}
                },
                "required": ["table_name", "run_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "verify_row_count_matches_expected",
            "description": "Post-remediation verification: confirms the table now has exactly the expected row count for a run_id. Use this AFTER a rerun to confirm recovery actually worked before declaring the incident resolved.",
            "parameters": {
                "type": "object",
                "properties": {
                    "table_name": {"type": "string", "description": "Table to verify, e.g. 'order_events'."},
                    "run_id": {"type": "string", "description": "The run_id to verify."},
                    "expected_row_count": {"type": "integer", "description": "The row count that should be present if recovery succeeded."}
                },
                "required": ["table_name", "run_id", "expected_row_count"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_sqs_queue_attributes",
            "description": "Real SQS queue health (message counts, in-flight count) -- use to detect a backed-up/stuck consumer or dead-letter queue buildup.",
            "parameters": {
                "type": "object",
                "properties": {"queue_url": {"type": "string", "description": "Full SQS queue URL."}},
                "required": ["queue_url"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "peek_sqs_messages",
            "description": "Reads (without deleting) messages from an SQS queue -- use to inspect a suspected poison-pill message causing repeated consumer failures.",
            "parameters": {
                "type": "object",
                "properties": {
                    "queue_url": {"type": "string", "description": "Full SQS queue URL."},
                    "max_messages": {"type": "integer", "description": "Max messages to peek (default 5)."}
                },
                "required": ["queue_url"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "list_sns_subscriptions",
            "description": "Lists real subscriptions on an SNS topic -- use to confirm alert routing is actually configured as expected.",
            "parameters": {
                "type": "object",
                "properties": {"topic_arn": {"type": "string", "description": "SNS topic ARN."}},
                "required": ["topic_arn"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "describe_rds_instance_status",
            "description": "Real RDS instance status (availability, storage, engine, Multi-AZ) -- use to check if a database is degraded/failing as the root cause of downstream job failures.",
            "parameters": {
                "type": "object",
                "properties": {"db_instance_identifier": {"type": "string", "description": "RDS DB instance identifier."}},
                "required": ["db_instance_identifier"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "describe_ecs_task_status",
            "description": "Real ECS service/task status (running vs desired count, recent stopped-task reasons) -- use for incidents where a containerized service (not a Lambda) is failing.",
            "parameters": {
                "type": "object",
                "properties": {
                    "cluster": {"type": "string", "description": "ECS cluster name."},
                    "service_name": {"type": "string", "description": "ECS service name."}
                },
                "required": ["cluster", "service_name"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "describe_step_function_execution",
            "description": "Real Step Functions execution status + recent failure events -- use for incidents orchestrated by a state machine to see which state failed and why.",
            "parameters": {
                "type": "object",
                "properties": {"execution_arn": {"type": "string", "description": "Step Functions execution ARN."}},
                "required": ["execution_arn"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "check_iam_role_permissions",
            "description": "Read-only IAM policy simulation -- use to diagnose AccessDenied-type failures (e.g. is the job's role missing a required permission) without ever modifying any policy.",
            "parameters": {
                "type": "object",
                "properties": {
                    "role_name": {"type": "string", "description": "IAM role name (not full ARN)."},
                    "action": {"type": "string", "description": "IAM action to check, e.g. 's3:GetObject'."},
                    "resource_arn": {"type": "string", "description": "Resource ARN to check against (default '*')."}
                },
                "required": ["role_name", "action"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_secret_metadata",
            "description": "Fetches Secrets Manager secret METADATA ONLY (never the secret value) -- use to check if a credential rotation happened recently as a possible cause of a sudden auth failure.",
            "parameters": {
                "type": "object",
                "properties": {"secret_id": {"type": "string", "description": "Secrets Manager secret ID or ARN."}},
                "required": ["secret_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "describe_ec2_instance_status",
            "description": "Real EC2 instance status checks (system + instance reachability) -- use when a self-hosted worker on EC2 is suspected to be unhealthy.",
            "parameters": {
                "type": "object",
                "properties": {"instance_id": {"type": "string", "description": "EC2 instance ID."}},
                "required": ["instance_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "list_recent_changes",
            "description": "Change intelligence: queries REAL CloudTrail events for a resource within a recent time window. ALWAYS check this before concluding root cause -- a recent deployment/config change correlated in time with a failure is a very strong causal signal, not just a coincidence.",
            "parameters": {
                "type": "object",
                "properties": {
                    "resource_id": {"type": "string", "description": "Resource name/ARN to check for recent changes, e.g. a Lambda function name."},
                    "window_minutes": {"type": "integer", "description": "How far back to look for changes (default 60)."}
                },
                "required": ["resource_id"]
            }
        }
    },
]


def _get_full_tools_schema() -> list:
    """Returns the tool schema list to advertise to the LLM: the base
    NemoGuard-metadata tools always, plus the real-AWS observability +
    data-integrity tools when the LocalStack lab is enabled."""
    if LOCALSTACK_LAB_ENABLED:
        return AGENT_TOOLS_SCHEMA + LOCALSTACK_LAB_TOOLS_SCHEMA
    return AGENT_TOOLS_SCHEMA


# Read-only-only tool names, safe to hand to a pure VERIFICATION agent (the
# Grounding Critic) that must be able to independently re-check evidence
# but must NEVER be able to execute a write/destructive action itself
# (spec §7.1 "Grounding and Safety Critic" -- it verifies, it does not act).
_READ_ONLY_TOOL_NAMES = {
    "query_logs", "get_cmdb_context", "get_runbook", "read_runbook_document",
    "query_cloudwatch_logs", "list_s3_objects", "read_s3_object",
    "describe_lambda_invocation", "check_table_staleness",
    "verify_row_count_matches_expected", "get_sqs_queue_attributes",
    "peek_sqs_messages", "list_sns_subscriptions",
    "describe_rds_instance_status", "describe_ecs_task_status",
    "describe_step_function_execution", "check_iam_role_permissions",
    "get_secret_metadata", "describe_ec2_instance_status",
    "list_recent_changes",
}


def _get_read_only_tools_schema() -> list:
    """Read-only subset of _get_full_tools_schema(), for agents (the
    Grounding Critic) that must independently verify claims but must never
    be able to execute a write/destructive capability themselves."""
    full = _get_full_tools_schema()
    return [t for t in full if t.get("function", {}).get("name") in _READ_ONLY_TOOL_NAMES]


async def execute_tool_call(tool_name: str, arguments: str) -> str:
    print(f"Executing tool {tool_name} with args {arguments}")
    try:
        args = json.loads(arguments)
    except:
        args = {}

    try:
        if tool_name == "query_logs":
            return query_logs(args.get("incident_id"), args.get("keyword", ""))
        elif tool_name == "get_cmdb_context":
            return get_cmdb_context(args.get("service_name", ""))
        elif tool_name == "get_runbook":
            return get_runbook(args.get("service_name", ""))
        elif tool_name == "read_runbook_document":
            return read_runbook_document(args.get("query", ""))
        elif LOCALSTACK_LAB_ENABLED and tool_name in (
            "query_cloudwatch_logs", "list_s3_objects", "read_s3_object",
            "describe_lambda_invocation", "check_table_staleness",
            "cleanup_partial_write", "verify_row_count_matches_expected",
            "get_sqs_queue_attributes", "peek_sqs_messages", "list_sns_subscriptions",
            "describe_rds_instance_status", "describe_ecs_task_status",
            "describe_step_function_execution", "check_iam_role_permissions",
            "get_secret_metadata", "describe_ec2_instance_status",
            "list_recent_changes",
        ):
            from src.domain.tools import aws_observability_tools as aws_tools
            if tool_name == "query_cloudwatch_logs":
                return aws_tools.query_cloudwatch_logs(args.get("log_group_name"), args.get("filter_pattern", ""), args.get("limit", 50))
            elif tool_name == "list_s3_objects":
                return aws_tools.list_s3_objects(args.get("bucket"), args.get("prefix", ""), args.get("max_keys", 20))
            elif tool_name == "read_s3_object":
                return aws_tools.read_s3_object(args.get("bucket"), args.get("key"))
            elif tool_name == "describe_lambda_invocation":
                return aws_tools.describe_lambda_invocation(args.get("function_name"))
            elif tool_name == "check_table_staleness":
                return aws_tools.check_table_staleness(args.get("table_name"), args.get("run_id"), args.get("expected_row_count"))
            elif tool_name == "cleanup_partial_write":
                return aws_tools.cleanup_partial_write(args.get("table_name"), args.get("run_id"), args.get("dry_run", True))
            elif tool_name == "verify_row_count_matches_expected":
                return aws_tools.verify_row_count_matches_expected(args.get("table_name"), args.get("run_id"), args.get("expected_row_count"))
            elif tool_name == "get_sqs_queue_attributes":
                return aws_tools.get_sqs_queue_attributes(args.get("queue_url"))
            elif tool_name == "peek_sqs_messages":
                return aws_tools.peek_sqs_messages(args.get("queue_url"), args.get("max_messages", 5))
            elif tool_name == "list_sns_subscriptions":
                return aws_tools.list_sns_subscriptions(args.get("topic_arn"))
            elif tool_name == "describe_rds_instance_status":
                return aws_tools.describe_rds_instance_status(args.get("db_instance_identifier"))
            elif tool_name == "describe_ecs_task_status":
                return aws_tools.describe_ecs_task_status(args.get("cluster"), args.get("service_name"))
            elif tool_name == "describe_step_function_execution":
                return aws_tools.describe_step_function_execution(args.get("execution_arn"))
            elif tool_name == "check_iam_role_permissions":
                return aws_tools.check_iam_role_permissions(args.get("role_name"), args.get("action"), args.get("resource_arn", "*"))
            elif tool_name == "get_secret_metadata":
                return aws_tools.get_secret_metadata(args.get("secret_id"))
            elif tool_name == "describe_ec2_instance_status":
                return aws_tools.describe_ec2_instance_status(args.get("instance_id"))
            elif tool_name == "list_recent_changes":
                return aws_tools.list_recent_changes(args.get("resource_id"), args.get("window_minutes", 60))
        else:
            return f"Error: Tool {tool_name} not found."
    except Exception as e:
        return f"Error executing {tool_name}: {str(e)}"
